# Generated by Django 4.0 on 2021-12-18 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tempRecord', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='temprecord',
            old_name='datetime',
            new_name='created_at',
        ),
    ]
